version: "3.7"
services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
    - "8090:80"
    environment:
    - "VUE_APP_API_BASE_URL=https://api.sikaeducation.com"
    - "PORT=80"
    volumes:
    - "./frontend:/app"
    command: /bin/sh -c "npm install && npm run serve"
  backend:
    build:
      context: ./backend
    environment:
    - "PORT=80"
    ports:
    - "8091:80"
    volumes:
    - "./backend:/app"
    command: /bin/sh -c "npm install && npm start"
